config/routes.rb
Rails.application.routes.draw do
  resources :arthicles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arthicle.rb
class Arthicle < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/arthicles_controller.rb
class ArthiclesController < ApplicationController
  before_action :set_arthicle, only: [:show, :edit, :update, :destroy]

  # GET /arthicles
  # GET /arthicles.json
  def index
    @arthicles = Arthicle.all
  end

  # GET /arthicles/1
  # GET /arthicles/1.json
  def show
  end

  # GET /arthicles/new
  def new
    @arthicle = Arthicle.new
  end

  # GET /arthicles/1/edit
  def edit
  end

  # POST /arthicles
  # POST /arthicles.json
  def create
    @arthicle = Arthicle.new(arthicle_params)

    respond_to do |format|
      if @arthicle.save
        format.html { redirect_to @arthicle, notice: 'Arthicle was successfully created.' }
        format.json { render :show, status: :created, location: @arthicle }
      else
        format.html { render :new }
        format.json { render json: @arthicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arthicles/1
  # PATCH/PUT /arthicles/1.json
  def update
    respond_to do |format|
      if @arthicle.update(arthicle_params)
        format.html { redirect_to @arthicle, notice: 'Arthicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @arthicle }
      else
        format.html { render :edit }
        format.json { render json: @arthicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arthicles/1
  # DELETE /arthicles/1.json
  def destroy
    @arthicle.destroy
    respond_to do |format|
      format.html { redirect_to arthicles_url, notice: 'Arthicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arthicle
      @arthicle = Arthicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def arthicle_params
      params.require(:arthicle).permit(:title, :author, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arthicles_helper.rb
module ArthiclesHelper
end

app/views/arthicles/_form.html.erb
<%= form_with(model: arthicle, local: true) do |form| %>
  <% if arthicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(arthicle.errors.count, "error") %> prohibited this arthicle from being saved:</h2>

      <ul>
      <% arthicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/arthicles/edit.html.erb
<h1>Editing Arthicle</h1>

<%= render 'form', arthicle: @arthicle %>

<%= link_to 'Show', @arthicle %> |
<%= link_to 'Back', arthicles_path %>

app/views/arthicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Arthicles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @arthicles.each do |arthicle| %>
      <tr>
        <td><%= arthicle.title %></td>
        <td><%= arthicle.author %></td>
        <td><%= arthicle.text %></td>
        <td><%= link_to 'Show', arthicle %></td>
        <td><%= link_to 'Edit', edit_arthicle_path(arthicle) %></td>
        <td><%= link_to 'Destroy', arthicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Arthicle', new_arthicle_path %>

app/views/arthicles/new.html.erb
<h1>New Arthicle</h1>

<%= render 'form', arthicle: @arthicle %>

<%= link_to 'Back', arthicles_path %>

app/views/arthicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @arthicle.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @arthicle.author %>
</p>

<p>
  <strong>Text:</strong>
  <%= @arthicle.text %>
</p>

<%= link_to 'Edit', edit_arthicle_path(@arthicle) %> |
<%= link_to 'Back', arthicles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>